[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && node src/server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production.deploy]
startCommand = "cd backend && node src/server.js"
