[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "wutong-backend"
source = "."

[services.wutong-backend]
variables = { PORT = "3000" }

[[services]]
name = "wutong-postgres"
plugin = "postgresql"

[[services]]
name = "wutong-redis" 
plugin = "redis"
