[build]
builder = "nixpacks"
buildCommand = "npm install && npx prisma generate && npx prisma migrate deploy"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
PORT = "0.0.0.0:$PORT"
NODE_ENV = "production"